### ISSUE TITLE
How to add a save button?

### ISSUE THREAD

**Issue by l0o0** [pyx/flask-simplemde#1]
I am trying to make a blog powered by flask. SimpleMDE for flask is really a easy tool to add an editor for markdown in flask. Butt I can not know how to add a button to save my post. I am new to html and js, I think `form` in html will helps, but the code in javascript seems difficult for me. Could you give me some hints to add a post-save function? ;)
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Flask-SimpleMDE example</title>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel='stylesheet' href='.{{ url_for("static", filename="css/simplemde.min.css") }}'>
    <script src='.{{ url_for("static", filename="js/simplemde.min.js") }}'></script>
  </head>
  <body>
    <form method='post' class='form' role='form'>
      <div class="form-group ">
        <input class="form-control" id="post_title" name="post_title" type="text" value="Title?">
      </div>
      <div class="form-group ">
        <textarea>
          Some Markdown Text Here
        </textarea>
      </div>

      <input class='btn btn-default' id='submit' name='submit' type='submit' value='Save'>
    </form>
    {{ simplemde.load }}
  </body>
</html>
```

**Comment by l0o0** [comment]
After reading some posts, I found how to do this.
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Editor</title>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel='stylesheet' href='.{{ url_for("static", filename="css/simplemde.min.css") }}'>
    <script src='.{{ url_for("static", filename="js/simplemde.min.js") }}'></script>
  </head>
  <body>
    <form method='post' class='form' role='form'>
      <div class="form-group " style="padding-top:10px">
        <input class="form-control" id="post_title" name="post_title" type="text" value="Title?">
      </div>
      <div class="form-group ">
        <input class="form-control" id="markdown" name="post_content" type="textarea" value="">
      </div>
      <div>
        <input class='btn btn-default' id='submit' name='submit' type='submit' value='Save'>
      </div>
    </form>
    {{ simplemde.load_id('markdown') }}
  </body>
</html>
```
Now `request.form['post_content']` return the raw text of markdown. But I found "\n" is missing in the content returned. Is there a way to maintain "\n"?

**Comment by pyx** [comment]
SimpleMDE, and many other javascript-powered HTML-based client-side Markdown editors usually
1. provide some help in Markdown editing (toolbar with buttons for header, url, etc.), think code-completion features in many programmer's editors.
2. render Markdown client-side for preview.
3. do not change the content of user input except when doing 1.

Remember those features are added on top of existing input elements (<input> with type "text" or <textarea>), and the javascript part of the editor does the magic (preview rendering, editing help) on client-side (although some provide APIs to communicate with the server while editing). When the user submit the form, that's when the editors' job end, and the application on server-side will receive whatever left in that input element, normally in Markdown format, unchanged by the editor.

For the original post, you need a way to submit the form, usually by a <button> or <input> with type "submit" inside <form> tag,  that's how HTML forms work, you can read more about HTML forms here:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form
https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms
 
As for your second post, try <textarea> instead of <input>, <textarea> is for multi-line input.

EDIT: corrected the type name for submit.

**Comment by l0o0** [comment]
@pyx I have find a way to do this. I can get raw markdown string if I put `post_content` in `textarea` tag. 
Thank you for you help.
